global:
  image:
    registry: reg.kyverno.io

fullnameOverride: kyverno
nameOverride: kyverno

admissionController:
  replicas: 1
  image:
    repository: kyverno/kyverno
    tag: "v1.17.1"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

backgroundController:
  enabled: true
  replicas: 1
  image:
    repository: kyverno/background-controller
    tag: "v1.17.1"

cleanupController:
  enabled: true

reportsController:
  enabled: true

crds:
  install: true

rbac:
  create: true