apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.16.0
      helm:
        valueFiles:
          - $myvalues/platform-helm/platform/ingress/cert-manager/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true