apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://kyverno.github.io/kyverno/'
      chart: kyverno
      targetRevision: 3.3.4
      helm:
        valueFiles:
          - $myvalues/platform-helm/platform/security/kyverno/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
