apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 26.0.1
      helm:
        valueFiles:
          - $myvalues/platform-helm/platform/observability/prometheus/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
