apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://traefik.github.io/charts'
      chart: traefik
      targetRevision: 31.0.0
      helm:
        valueFiles:
          - $myvalues/platform-helm/platform/ingress/traefik/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
