apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config-cli
  namespace: identity
data:
  platform-realm.yaml: |
    realm: platform
    enabled: true
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    resetPasswordAllowed: true
    clients:
      - clientId: argocd
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: ${ARGOCD_CLIENT_SECRET}
        redirectUris:
          - "https://argo.dev.myplatformproject.com/auth/callback"
        webOrigins:
          - "https://argo.dev.myplatformproject.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: groups
              jsonType.label: String
      - clientId: grafana
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: ${GRAFANA_CLIENT_SECRET}
        redirectUris:
          - "https://grafana.dev.myplatformproject.com/login/generic_oauth"
        webOrigins:
          - "https://grafana.dev.myplatformproject.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: groups
              jsonType.label: String
      - clientId: backstage
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: ${BACKSTAGE_CLIENT_SECRET}
        redirectUris:
          - "https://backstage.dev.myplatformproject.com/api/auth/oidc/handler/frame"
        webOrigins:
          - "https://backstage.dev.myplatformproject.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: groups
              jsonType.label: String
      - clientId: falco-sidekick-proxy
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: ${FALCO_PROXY_CLIENT_SECRET}
        redirectUris:
          - "https://falco-sidekick.dev.myplatformproject.com/oauth2/callback"
        webOrigins:
          - "https://falco-sidekick.dev.myplatformproject.com"
        defaultClientScopes:
          - profile
          - email
          - roles
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: groups
              jsonType.label: String
    groups:
      - name: platform-admins
      - name: platform-readonly

