apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: developer-portal
type: Opaque
stringData:
  POSTGRES_PASSWORD: "replace-with-strong-db-password"
  AUTH_KEYCLOAK_CLIENT_SECRET: "replace-with-keycloak-client-secret"
  BACKEND_SECRET: "replace-with-long-random-backend-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres-auth
  namespace: developer-portal
type: Opaque
stringData:
  postgres-password: "replace-with-strong-admin-password"
  password: "replace-with-strong-db-password"
