name: Remove Preview GitOps

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:

  cleanup:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Remove preview
      run: |
        rm -rf "platform-helm/envs/preview/microservices/preview-${{ inputs.pr_number }}"

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email actions@github.com
        git add "platform-helm/envs/preview/microservices/preview-${{ inputs.pr_number }}/"
        git diff --staged --quiet || git commit -m "remove preview env preview-${{ inputs.pr_number }}"
        git push