image:
  repository: traefik
  tag: v3.1.2
  digest: ""

deployment:
  replicas: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev.myplatformproject.com
    external-dns.alpha.kubernetes.io/ttl: "60"

metrics:
  prometheus:
    enabled: true
    service:
      enabled: true
    serviceMonitor:
      enabled: false
