image:
  # NOTE: The image is updated by the GitHub Actions pipelines and is deployed via ArgoCD.
  repository: "016257615702.dkr.ecr.us-east-1.amazonaws.com/api-gateway"
  tag: "b18fd22c61df9da22ca42a89df7180ad2f3e9374"
ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: api.preview-5.dev.example.local
      paths:
        - path: /
          pathType: Prefix
env:
  PORT: "8080"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "kafka.message-broker.svc.cluster.local:9092"
  WRITER_GRPC_PORT: "writer:5000"
  READER_GRPC_PORT: "reader:5001"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
