image:
  registry: registry-1.docker.io
  repository: bitnami/mongodb
  tag: latest

architecture: standalone
replicaCount: 1

auth:
  enabled: true
  rootUser: admin
  existingSecret: mongodb-auth

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPU: 70
