image:
  repository: grafana/grafana
  tag: 11.2.0
  digest: ""

admin:
  existingSecret: grafana-admin

plugins:
  - grafana-piechart-panel 1.6.4
  - grafana-clock-panel 2.1.4
  - isovalent-hubble-datasource 1.0.0

persistence:
  enabled: true
  size: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPU: "70"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 5

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
    external-dns.alpha.kubernetes.io/target: "18.234.67.136"
  hosts:
    - grafana.dev.myplatformproject.com
  tls:
    - secretName: grafana-dev-myplatformproject-com-tls
      hosts:
        - grafana.dev.myplatformproject.com

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local
        isDefault: true
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.observability.svc.cluster.local:16686
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
      - name: Hubble
        uid: hubble
        type: isovalent-hubble-datasource
        access: proxy
        jsonData:
          prometheusDatasourceUid: prometheus
