# This is the base values chart for the reader microservice.
# For environment-specific overrides, see the files in the envs directory.

nameOverride: "reader"
fullnameOverride: "reader"

replicaCount: 1
image:
  repository: "016257615702.dkr.ecr.us-east-1.amazonaws.com/reader"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: grpc
      port: 5001
      targetPort: 5001

probes:
  liveness:
    path: /health
    port: 5001

env:
  GRPC_PORT: ":5001"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "kafka.message-broker.svc.cluster.local:9092"
  PROMETHEUS_URL: "http://prometheus-server.observability.svc.cluster.local"
  JAEGER_HOST: "jaeger.observability.svc.cluster.local"
  MONGO_DB: "products"
  REDIS_ADDR: "redis.database.svc.cluster.local:6379"
  POSTGRES_HOST: "postgresql.database.svc.cluster.local"
  POSTGRES_PORT: "5432"

secretEnv:
  MONGO_URI:
    secretName: mongo-uri-secret
    secretKey: MONGO_URI

livenessProbe:
  tcpSocket:
    port: 5001
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  tcpSocket:
    port: 5001
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

startupProbe:
  tcpSocket:
    port: 5001
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 24

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi