image:
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0
  pullPolicy: IfNotPresent

auth:
  existingSecret: keycloak-auth

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

startupProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1

ingress:
  enabled: true
  hostname: keycloak.dev.myplatformproject.com
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
    external-dns.alpha.kubernetes.io/target: "34.228.167.63"
  tls: true

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0
  auth:
    username: keycloak
    database: bitnami_keycloak
    existingSecret: keycloak-postgresql-auth
    secretKeys:
      userPasswordKey: password
  primary:
    persistence:
      enabled: true
      size: 2Gi
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
    startupProbe:
      enabled: true
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30