image:
  registry: registry-1.docker.io
  repository: bitnami/keycloak
  tag: 26.3.3-debian-12-r0

auth:
  existingSecret: keycloak-auth

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-postgresql-auth
  primary:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: gp3
