apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: kafka
      targetRevision: 32.4.3
      helm:
        valueFiles:
          - $myvalues/platform-helm/applications/app-dependencies/message-queue/kafka/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: message-broker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true