apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: mongodb
      targetRevision: 18.6.11 
      helm:
        valueFiles:
          - $myvalues/platform-helm/applications/app-dependencies/databases/mongodb/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database # Isolating databases in their own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true