apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: redis
      targetRevision: 20.0.1
      helm:
        valueFiles:
          - $myvalues/platform-helm/applications/app-dependencies/databases/redis/values.yaml
    - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
      targetRevision: HEAD
      ref: myvalues
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true