apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: dev-microservices-hubble-l7-visibility
  namespace: dev-microservices
spec:
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: dev-microservices
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
            - port: "5001"
              protocol: TCP
          rules:
            http:
              - {}
