image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 4.0.0-debian-12-r10
  pullPolicy: IfNotPresent

auth:
  enabled: false

kraft:
  enabled: true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi

broker:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 1Gi
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPU: 70
listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
  controller:
    protocol: PLAINTEXT
    containerPort: 9093

listenerSecurityProtocolMap:
  CLIENT: PLAINTEXT
  INTERNAL: PLAINTEXT
  CONTROLLER: PLAINTEXT
metrics:
  kafka:
    enabled: false
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false