image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.8.0-debian-12-r4
  pullPolicy: IfNotPresent

auth:
  enabled: false

kraft:
  enabled: true

controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  startupProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30

broker:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 1Gi
  autoscaling:
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPU: 70
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  startupProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
listeners:
  client:
    protocol: PLAINTEXT
    containerPort: 9092
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
  controller:
    protocol: PLAINTEXT
    containerPort: 9093

listenerSecurityProtocolMap:
  CLIENT: PLAINTEXT
  INTERNAL: PLAINTEXT
  CONTROLLER: PLAINTEXT
metrics:
  kafka:
    enabled: false
  jmx:
    enabled: false
  serviceMonitor:
    enabled: false