server:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.54.1
    digest: ""
  persistentVolume:
    enabled: true
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 3Gi
  startupProbe:
    enabled: true
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 30

alertmanager:
  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.27.0
  persistentVolume:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30