global:
  clusterId: dev-k3s
  prometheus:
    enabled: false
    fqdn: http://prometheus-server.observability.svc.cluster.local
    insecureSkipVerify: false
  federatedStorage:
    config: |-
      type: S3
      config:
        bucket: dev-kubecost-store-platform-engineering-project
        endpoint: s3.amazonaws.com
        region: us-east-1
        insecure: false

prometheus:
  server:
    global:
      external_labels:
        cluster_id: dev-k3s

kubecostModel:
  image: "gcr.io/kubecost1/cost-model"
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 10

kubecostFrontend:
  image: "gcr.io/kubecost1/frontend"
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 10
