image:
  # NOTE: The image is updated by the GitHub Actions pipelines and is deployed via ArgoCD.
  repository: "016257615702.dkr.ecr.us-east-1.amazonaws.com/api-gateway"
  tag: "e90cc3c8577262e719487acb0ccac39645d4d318"
ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: api.dev.example.local
      paths:
        - path: /
          pathType: Prefix

env:
  HTTP_PORT: ":5001"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "kafka.message-broker.svc.cluster.local:9092"
  PROMETHEUS_URL: "http://prometheus-server.observability.svc.cluster.local"
  READER_SERVICE: "reader.dev-microservices.svc.cluster.local:5003"

livenessProbe:
  httpGet:
    path: /live
    port: 3001
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 3001
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /live
    port: 3001
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 24

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi