image:
  repository: "016257615702.dkr.ecr.us-east-1.amazonaws.com/reader"
  tag: "e90cc3c8577262e719487acb0ccac39645d4d318"

env:
  GRPC_PORT: "5001"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "kafka.message-broker.svc.cluster.local:9092"
  MONGO_DB: "products"
  REDIS_ADDR: "redis.database.svc.cluster.local:6379"
  POSTGRES_HOST: "postgresql.database.svc.cluster.local"
  POSTGRES_PORT: "5432"

secretEnv:
  MONGO_URI:
    secretName: mongo-uri-secret
    secretKey: MONGO_URI

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi