image:
  repository: "016257615702.dkr.ecr.us-east-1.amazonaws.com/writer"
  tag: "e90cc3c8577262e719487acb0ccac39645d4d318"

env:
  GRPC_PORT: ":5000"
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "kafka.message-broker.svc.cluster.local:9092"
  POSTGRES_HOST: "postgresql.database.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "products"
  POSTGRES_USER: "postgres"
  REDIS_ADDR: "redis.database.svc.cluster.local:6379"

secretEnv:
  POSTGRES_PASSWORD:
    secretName: writer-db-secret
    secretKey: POSTGRES_PASSWORD
  MONGO_URI:
    secretName: mongo-uri-secret
    secretKey: MONGO_URI

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi