apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-microservices
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: api-gateway
          - service: reader
          - service: writer
  template:
    metadata:
      name: 'dev-{{service}}'
      namespace: dev-microservices
      labels:
        environment: dev
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
        targetRevision: HEAD
        path: platform-helm/applications
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            # Base values per service (e.g. microservices/api-gateway/values.yaml)
            - 'microservices/{{service}}/values.yaml'
            # Dev environment overrides (e.g. microservices/envs/dev/api-gateway-values.yaml)
            - 'microservices/envs/dev/{{service}}-values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dev-microservices
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true