apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-dependency-apps
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - list:
        elements:
          - name: mongodb
            chartPath: platform-helm/charts/external/mongodb
            targetNamespace: database
            valuesPath: platform-helm/envs/dev/applications/app-dependencies/databases/mongodb/values.yaml
            syncWave: "1"

          - name: postgresql
            chartPath: platform-helm/charts/external/postgresql
            targetNamespace: database
            valuesPath: platform-helm/envs/dev/applications/app-dependencies/databases/postgresdb/values.yaml
            syncWave: "1"

          - name: redis
            chartPath: platform-helm/charts/external/redis
            targetNamespace: database
            valuesPath: platform-helm/envs/dev/applications/app-dependencies/databases/redis/values.yaml
            syncWave: "1"

          - name: kafka
            chartPath: platform-helm/charts/external/kafka
            targetNamespace: message-broker
            valuesPath: platform-helm/envs/dev/applications/app-dependencies/message-queue/kafka/values.yaml
            syncWave: "2"

  template:
    metadata:
      name: 'dev-{{.name}}'
      namespace: argocd
      labels:
        environment: dev
        tier: dependency
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'

    spec:
      project: default

      source:
        repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
        targetRevision: main
        path: '{{.chartPath}}'
        helm:
          releaseName: '{{.name}}'
          valueFiles:
            - '../../../../{{.valuesPath}}'

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.targetNamespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true