apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-microservices
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - list:
        elements:
          - service: api-gateway
            syncWave: "10"
          - service: reader
            syncWave: "10"
          - service: writer
            syncWave: "10"

  template:
    metadata:
      name: 'dev-{{.service}}'
      namespace: argocd
      labels:
        environment: dev
        tier: microservices
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'

    spec:
      project: default

      sources:
        # Base microservice Helm chart
        - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
          targetRevision: main
          path: platform-helm/general/microservices
          helm:
            releaseName: '{{.service}}'
            ignoreMissingValueFiles: false
            valueFiles:
              - '{{.service}}/values.yaml'
              - '$myvalues/platform-helm/envs/dev/applications/microservices/{{.service}}-values.yaml'

        # Values repo reference
        - repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
          targetRevision: main
          ref: myvalues

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dev-microservices

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true