apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-policy-apps
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - list:
        elements:
          - name: kyverno-policies
            sourcePath: platform-security/kyverno
            targetNamespace: security
            syncWave: "6"   # after kyverno (wave 3)

  template:
    metadata:
      name: 'dev-{{.name}}'
      namespace: argocd
      labels:
        environment: dev
        tier: policy
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'

    spec:
      project: default

      source:
        repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
        targetRevision: main
        path: '{{.sourcePath}}'
        directory:
          recurse: true

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.targetNamespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true