jaeger:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
      external-dns.alpha.kubernetes.io/target: "18.234.67.136"
    hosts:
      - jaeger.dev.myplatformproject.com
    tls:
      - secretName: jaeger-dev-myplatformproject-com-tls
        hosts:
          - jaeger.dev.myplatformproject.com

