kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "127.0.0.1" # Limits access to your localhost only
  - containerPort: 443
    hostPort: 443
    listenAddress: "127.0.0.1"