image:
  repository: quay.io/cilium/cilium
  tag: "v1.19.1"

operator:
  replicas: 1
  skipCRDCreation: false
  image:
    repository: quay.io/cilium/operator
    tag: "v1.19.1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

crdWaitTimeout: 10m

startupProbe:
  failureThreshold: 300
  periodSeconds: 2

livenessProbe:
  failureThreshold: 10
  periodSeconds: 30
  requireK8sConnectivity: false

readinessProbe:
  failureThreshold: 3
  periodSeconds: 30

hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - "dns:query;ignoreAAAA"
      - "drop"
      - "tcp"
      - "flow"
      - "httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
    serviceMonitor:
      enabled: false
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
  ui:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
        external-dns.alpha.kubernetes.io/target: "18.234.67.136"
      hosts:
        - hubble.dev.myplatformproject.com
      tls:
        - secretName: hubble-dev-myplatformproject-com-tls
          hosts:
            - hubble.dev.myplatformproject.com