image:
  repository: quay.io/cilium/cilium
  tag: "v1.19.1"

operator:
  replicas: 1
  skipCRDCreation: false
  image:
    repository: quay.io/cilium/operator
    tag: "v1.19.1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

crdWaitTimeout: 10m

startupProbe:
  failureThreshold: 300
  periodSeconds: 2

livenessProbe:
  failureThreshold: 10
  periodSeconds: 30
  requireK8sConnectivity: false

readinessProbe:
  failureThreshold: 3
  periodSeconds: 30

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-route53-dns01
      hosts:
        - hubble.dev.myplatformproject.com
      tls:
        - secretName: hubble-dev-myplatformproject-com-tls
          hosts:
            - hubble.dev.myplatformproject.com