provider:
  name: aws

policy: sync
registry: txt
txtOwnerId: k3s-dev-myplatformproject-com

domainFilters:
  - myplatformproject.com

sources:
  - ingress

aws:
  zoneType: public

env:
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_DEFAULT_REGION
    value: us-east-1
