name: Security Scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      image_artifact:
        required: true
        type: string

jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image_artifact }}
        path: .

    - name: Load image
      run: |
        docker load -i image.tar

    - uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ inputs.image }}
        severity: CRITICAL,HIGH
        exit-code: 1