apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infrastructure-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
    targetRevision: HEAD
    path: platform-gitops/apps
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
# 2. ApplicationSets (dev, prod, preview)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-workloads-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Muhammad-Ibra3/platform-engineering-project.git'
    targetRevision: HEAD
    path: platform-gitops/env-appsets
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true