image:
  repository: docker.io/falcosecurity/falco
  tag: "0.43.0"
  pullPolicy: IfNotPresent

driver:
  enabled: true
  kind: modern_ebpf

  # modern eBPF does not need the separate driver-loader init container
  loader:
    enabled: false

falcoctl:
  image:
    registry: docker.io
    repository: falcosecurity/falcoctl
    tag: "0.12.2"
    pullPolicy: IfNotPresent

  # disabled for testing
  artifact:
    install:
      enabled: false
    follow:
      enabled: false

falco:
  grpc:
    enabled: true
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d

customRules: {}

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi