image:
  repository: falcosecurity/falco
  tag: "0.43.0"

falco:
  grpc:
    enabled: true
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d

customRules: {}

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

metrics:
  enabled: true

healthChecks:
  startupProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 24
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 15
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3