name: Push Image

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      image_tag:
        required: false
        type: string
        default: ${{ github.sha }}
      image_artifact:
        required: true
        type: string

    secrets:
      AWS_ROLE:
        required: true
      ECR_REGISTRY:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image_artifact }}
        path: .

    - name: Load image
      run: |
        docker load -i image.tar

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: us-east-1

    - uses: aws-actions/amazon-ecr-login@v2

    - name: Tag image for registry
      run: |
        docker tag \
          "local/${{ inputs.service }}:${{ inputs.image_tag }}" \
          "${{ secrets.ECR_REGISTRY }}/${{ inputs.service }}:${{ inputs.image_tag }}"

    - name: Push image
      run: |
        docker push \
          "${{ secrets.ECR_REGISTRY }}/${{ inputs.service }}:${{ inputs.image_tag }}"
