name: "[DEPRECATED] Sign Image"

on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated workflow
        shell: bash
        run: |
          echo "::error file=.github/workflows/ci-tasks/sign-image.yaml,title=Deprecated workflow::sign-image.yaml is deprecated and removed. Use .github/workflows/ci-tasks/push-and-sign.yaml in your pipeline."
          exit 1